
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'






@Entity("AccountSnapshotLP")
export class AccountSnapshotLP  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	lastShare: BigInt

	@Required
	@Column("BigInt")
	lastCumulativeRate: BigInt

	@Required
	@Column("BigInt")
	lastCummulativeRatePenPie: BigInt

	@Required
	@Column("BigInt")
	lastSharePenPie: BigInt

	@Required
	@Column("BigInt")
	lastCummulativeRateEQB: BigInt

	@Required
	@Column("BigInt")
	lastShareEQB: BigInt

  constructor(data: Partial<AccountSnapshotLP>) {}

}

@Entity("RateSnapshotLP")
export class RateSnapshotLP  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	cummulativeRate: BigInt

	@Required
	@Column("BigInt")
	cummulativeRatePenPie: BigInt

	@Required
	@Column("BigInt")
	cummulativeRateEQB: BigInt

  constructor(data: Partial<RateSnapshotLP>) {}

}

@Entity("AccountSnapshotSY")
export class AccountSnapshotSY  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	lastBalance: BigInt

  constructor(data: Partial<AccountSnapshotSY>) {}

}

@Entity("AccountSnapshotYT")
export class AccountSnapshotYT  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	lastUpdatedAt: BigInt

	@Required
	@Column("BigInt")
	lastImpliedHolding: BigInt

  constructor(data: Partial<AccountSnapshotYT>) {}

}

@Entity("RerunSnapshot")
export class RerunSnapshot  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	updatedAt: BigInt

	@Required
	@Column("Boolean")
	ended: Boolean

  constructor(data: Partial<RerunSnapshot>) {}

}


const source = `type AccountSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastShare: BigInt!
  lastCumulativeRate: BigInt!
  lastCummulativeRatePenPie: BigInt!
  lastSharePenPie: BigInt!
  lastCummulativeRateEQB: BigInt!
  lastShareEQB: BigInt!
}

type RateSnapshotLP @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  cummulativeRate: BigInt!
  cummulativeRatePenPie: BigInt!
  cummulativeRateEQB: BigInt!
}

type AccountSnapshotSY @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastBalance: BigInt!
}

type AccountSnapshotYT @entity {
  id: ID!
  lastUpdatedAt: BigInt!
  lastImpliedHolding: BigInt!
}

type RerunSnapshot @entity {
  id: ID!
  updatedAt: BigInt!
  ended: Boolean!
}

`
DatabaseSchema.register({
  source,
  entities: {
    "AccountSnapshotLP": AccountSnapshotLP,
		"RateSnapshotLP": RateSnapshotLP,
		"AccountSnapshotSY": AccountSnapshotSY,
		"AccountSnapshotYT": AccountSnapshotYT,
		"RerunSnapshot": RerunSnapshot
  }
})
